import type { Metadata } from "next";
import { Providers } from "./providers";
import { fonts } from "./fonts";
import localFont from "next/font/local";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Devan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.montserrat.variable} ${fonts.openSans.variable}`}
      >
        <Providers>{children}</Providers>
        {/* {children} */}
      </body>
    </html>
  );
}
