import type { Metadata } from "next";
import Header from "./components/Header/Header";

  export const metadata: Metadata = {
  title: "Devan's Portfolio",
  description: "Generated by create next app",
};

export default function Home() {

  return (
    <div className="container">
      <Header/>
    </div>
  );
}
